In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]]
3


In [5]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [7]:
arr = np.array([1, 2, 3, 4], dtype=complex)
print(arr.dtype)

complex128


In [8]:
arr = np.array([1, 2, 3, 4], dtype=float)
print(arr.dtype)

float64


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)
print(arr.shape)

6
(2, 3)


In [13]:
arr = np.arange(30)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [16]:
arr = np.arange(0, 22, 3)
print(arr)

[ 0  3  6  9 12 15 18 21]


In [19]:
arr = np.array([0, 1, 2, 3, 4])
print(arr[-1])


4


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0][-1])

3


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[1:8:2])

[2 3 4 5]
[5 6 7 8 9]
[1 2 3 4]
[2 4 6 8]


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])
print(arr[::2])

[5 6]
[1 3 5 7]


In [37]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 3])
print(arr[0:2, 1:4])

[7 8 9]
[4 9]
[[2 3 4]
 [7 8 9]]


In [38]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.shape)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)

newarr = arr.reshape(2, 3, 2)
print(newarr)
print(newarr.shape)

(12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
#newarr = arr.reshape(3, 3) #error because the total number of elements is not the same as the original array
print(newarr)
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
